name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the self-hosted runner you set up
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check and Deploy YAML files
        run: |
          # Copy all .yaml and .yml files to /etc/sectigo
          for file in *.yaml *.yml; do
            if [ -f "$file" ]; then
              sudo cp "$file" /etc/sectigo/
              echo "Deployed $file to /etc/sectigo/"
            fi
          done

