name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted  # Use the self-hosted runner you set up
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Running a deployment script!"

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.name "abdealipython"
          git config --global user.email "abdealipython@gmail.com"
          git add .
          git diff --cached --quiet || echo "Changes detected."

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: |
          git commit -m "Changes"
          git push origin main
